<?php
/**
 * Created by PhpStorm.
 * User: wll
 * Date: 18-4-18
 * Time: 下午8:22
 */

namespace App\Sock\Controller;

use EasySwoole\Core\Socket\Response;
use EasySwoole\Core\Socket\AbstractInterface\WebSocketController;
use EasySwoole\Core\Swoole\ServerManager;
use EasySwoole\Core\Swoole\Task\TaskManager;

class WebSocketTest extends WebSocketController
{

    public function  actionNotFound(?string $actionName)
    {
        //parent::actionNotFound($actionName); // TODO: Change the autogenerated stub
        $this->response()->write("{$actionName} not found");
    }

    public function test(){
        $this->response()->write(time());
    }

    public function args(){
        var_dump($this->request()->getArgs());
    }

    public function delay(){
        $client = $this->client();
        TaskManager::async(function () use ($client){
            sleep(2);
            Response::response($client, 'this is delay mesage at '.time());
            ServerManager::getInstance()->getServer()->close($client->getFd());
        });
    }

    public function who(){
        $this->response()->write('you fd is '.$this->client()->getFd());
    }

}